testing/kpi/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.kpi, name='kpi'),
    #url(r'^add', views.kpi_add, name='kpi_add'),
]

testing/testing/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    # Examples:
    # url(r'^$', 'testing.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('kpi.urls'), name='kpi'),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth_views.login),
    url(r'^accounts/logout/$', auth_views.logout_then_login),
    url(r'^nested_admin/', include('nested_admin.urls')),
]

testing/kpi/models.py
#coding=utf-8
from django.db import models
from django.forms import ModelForm
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.contrib.auth.models import Permission

input_formats = ['%d-%m-%Y']
YEAR_CHOICES = ('2015', '2016')

class TermManager(models.Manager):
    def for_user(self, user):
        return super(TermManager, self).get_query_set().filter(user=user)

class Term(models.Model):
	term = models.DateField('Срок')
	date = models.DateField('Дата закрытия')
	user = models.ForeignKey('auth.User')
	objects = TermManager()
	
	class Meta:
		verbose_name = 'KPI'
		verbose_name_plural = 'KPI сотрудников'

	def __unicode__(self):
		return str(self.term)[:7]


class Kpi(models.Model):
	name = models.CharField('KPI', max_length=200)
	dates = models.ForeignKey(Term)

	def __unicode__(self):
		return self.name

class Aim(models.Model):
	POSITIVE = 'Pos'
	NEUTRAL = 'Neu'
	NEGATIVE = 'Neg'
	DIFFERENCE_CHOICES = (
		(NEGATIVE, 'Отрицательно'),
		(NEUTRAL, 'Норма'),
		(POSITIVE, 'Положительно'),
    )

	aim_name = models.CharField('Задача', max_length=200)
	value = models.CharField('Значение', max_length=200)
	difference = models.CharField('Разница', max_length=200, 
		choices=DIFFERENCE_CHOICES, default=NEGATIVE)
	commentary = models.CharField('Комментарии', max_length=500)
	kpi = models.ForeignKey(Kpi)

	class Meta:
		verbose_name = 'Задача'
		verbose_name_plural = 'Задачи'
		

	def __unicode__(self):
		return self.aim_name

testing/kpi/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponsePermanentRedirect
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from models import Kpi, Aim, Term


@login_required(login_url='/accounts/login/')
def kpi(request):
	user = request.user
	terms = Term.objects.filter(user=user)
	for term in terms:
		term.kpis = Kpi.objects.filter(dates=term)
		term.date = str(term.date)[:7]
		term.term = str(term.term)[:7]
		for kpi in term.kpis:
			kpi.aims = Aim.objects.filter(kpi=kpi)
	return render_to_response('kpi.html', {'terms':terms })

testing/kpi/templates/kpi.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
{% load staticfiles %}
<link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">
<link href="{% static "bootstrap/css/bootstrap-responsive.css" %}" rel="stylesheet">
<script src="{% static "bootstrap/js/bootstrap.js" %}"></script>
<body>
    {% block content %}

    {% for term in terms %}
    <table class='table table-bordered' border=1px>
   	<tr>
    <th id="date">Дата закрытия</th>
    <th id="term">Срок</th>
    <th id="kpi">KPI</th>
    <th id="aim_name">Задача</th>
    <th id="aim_value">Значение</th>
    <th id="aim_diff">Разница</th>
    <th id="aim_comm">Комментарий</th>
	<tr>
		{% for kpi in term.kpis %}
			{% for aim in kpi.aims %}
			<tr>
				<td>{{ term.date }}</td>
				<td>{{ term.term }}</td>
				<td>{{ kpi.name }}</td>
				<td>{{ aim.aim_name }}</td>
				<td>{{ aim.value }}</td>
				{% if aim.get_difference_display == 'Норма' %}
					<td bgcolor = 'yellow'>{{ aim.get_difference_display}}</td>
				{% elif aim.get_difference_display == 'Отрицательно' %}
					<td bgcolor = 'red'>{{ aim.get_difference_display}}</td>
				{% elif aim.get_difference_display == 'Положительно'%}
					<td bgcolor = 'green'>{{ aim.get_difference_display}}</td>
				{% endif %}	
				<td>{{ aim.commentary }}</td>
			</tr>
			{% endfor %}
		
		{% endfor %}

	<p></p>
	</table>
	{% endfor %}

    {% endblock %}


    <form action="/accounts/logout/" method="get">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Logout" />
</form>
</body>
</html>

testing/kpi/templates/kpi_add.html
<html>
    <head>
    </head>

    <body>
        <form method="post" action="/add">
            
            {% csrf_token %}
            <form id="form2" method="post">
                <table border=1px>
                {% for field in form2 %}
                <tr>
                    <td>{{ field.label }} : 
                    {{ field }}</td>
                    {% endfor %}
                 </tr>
            </form>

           
            <form id="form1" method="post">   
                <table border=1px>
                {% for field in form1 %}
                <tr>
                <td>{{ field.label }} : 
                    {{ field }}</td>
                </tr>
                {% endfor %}
            </form>
        
        <input type="submit" name="submit" value="" />                    
        </form>
    </body>

</html>